// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr7Se0XdXoU208Njv4vhBYW4tgnpiM5lE',
    appId: '1:848782138701:web:6749ddabb6a129b6962b04',
    messagingSenderId: '848782138701',
    projectId: 'foodgo-89c03',
    authDomain: 'foodgo-89c03.firebaseapp.com',
    storageBucket: 'foodgo-89c03.firebasestorage.app',
    measurementId: 'G-2Z3N0GTKVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUTS0bvsdnJsqho_c-skIKvkyUNA0wWEA',
    appId: '1:848782138701:android:4b34354bc487b49c962b04',
    messagingSenderId: '848782138701',
    projectId: 'foodgo-89c03',
    storageBucket: 'foodgo-89c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IWy3jUkEcCbR1ZXkzzav-7y-S6jzoOA',
    appId: '1:848782138701:ios:449517cacf08c1e2962b04',
    messagingSenderId: '848782138701',
    projectId: 'foodgo-89c03',
    storageBucket: 'foodgo-89c03.firebasestorage.app',
    iosBundleId: 'com.booker.foodgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IWy3jUkEcCbR1ZXkzzav-7y-S6jzoOA',
    appId: '1:848782138701:ios:6bcb0546e9a0310c962b04',
    messagingSenderId: '848782138701',
    projectId: 'foodgo-89c03',
    storageBucket: 'foodgo-89c03.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr7Se0XdXoU208Njv4vhBYW4tgnpiM5lE',
    appId: '1:848782138701:web:c43aabea3879f51a962b04',
    messagingSenderId: '848782138701',
    projectId: 'foodgo-89c03',
    authDomain: 'foodgo-89c03.firebaseapp.com',
    storageBucket: 'foodgo-89c03.firebasestorage.app',
    measurementId: 'G-3SEDP04S71',
  );
}
